import { useState } from 'react'
import Navbar from '../components/Navbar'
import './Certification.css'

function Certification() {
  const [product, setProduct] = useState('')

  const steps = [
    {
      number: '01',
      icon: '🔎',
      title: 'Identify the Standard',
      description:
        'Find the applicable Indian Standard for your product.'
    },
    {
      number: '02',
      icon: '📋',
      title: 'Choose Certification Scheme',
      description:
        'Understand the applicable BIS conformity assessment scheme.'
    },
    {
      number: '03',
      icon: '📄',
      title: 'Prepare Documents',
      description:
        'Prepare the required technical and supporting documents.'
    },
    {
      number: '04',
      icon: '🧪',
      title: 'Product Testing',
      description:
        'Get the product tested through an applicable recognized laboratory.'
    },
    {
      number: '05',
      icon: '🏭',
      title: 'Inspection & Assessment',
      description:
        'BIS may assess the manufacturing and quality control process.'
    },
    {
      number: '06',
      icon: '✓',
      title: 'Licence & Compliance',
      description:
        'Complete the process and maintain ongoing compliance.'
    }
  ]

  const handleSearch = (e) => {
    e.preventDefault()

    if (!product.trim()) return

    alert(
      `Certification guidance for "${product}" will be generated by BIS AI.`
    )
  }

  return (
    <>
      <Navbar />

      <main className="certification-page">

        {/* ================= HERO ================= */}

        <section className="certification-hero">

          <div className="certification-hero-content">

            <span className="certification-label">
              BIS CERTIFICATION GUIDANCE
            </span>

            <h1>
              Navigate BIS
              <span> Certification</span>
            </h1>

            <p>
              Understand certification requirements, applicable
              standards, testing and compliance steps for your product.
            </p>

            {/* Product Search */}

            <form
              className="certification-search"
              onSubmit={handleSearch}
            >

              <span className="certification-search-icon">
                🔎
              </span>

              <input
                type="text"
                value={product}
                onChange={(e) => setProduct(e.target.value)}
                placeholder="Enter your product name..."
              />

              <button type="submit">
                Get Guidance →
              </button>

            </form>

            <div className="certification-note">
              ✨ AI-powered guidance based on BIS standards and services
            </div>

          </div>

        </section>

        {/* ================= MAIN ================= */}

        <section className="certification-main">

          <div className="certification-container">

            {/* Overview */}

            <div className="certification-overview">

              <div>

                <span className="section-label">
                  CERTIFICATION JOURNEY
                </span>

                <h2>
                  From product to BIS certification
                </h2>

              </div>

              <p>
                Follow the major stages involved in understanding
                and obtaining BIS certification. The exact process
                depends on the product and applicable scheme.
              </p>

            </div>

            {/* Steps */}

            <div className="certification-steps">

              {steps.map((step, index) => (

                <div
                  className="certification-step"
                  key={step.number}
                >

                  <div className="step-number">
                    {step.number}
                  </div>

                  <div className="step-icon">
                    {step.icon}
                  </div>

                  <div className="step-content">

                    <h3>
                      {step.title}
                    </h3>

                    <p>
                      {step.description}
                    </p>

                  </div>

                  {index !== steps.length - 1 && (
                    <div className="step-line"></div>
                  )}

                </div>

              ))}

            </div>

            {/* ================= INFORMATION GRID ================= */}

            <div className="certification-info-grid">

              {/* Standards */}

              <div className="certification-info-card">

                <div className="info-card-icon">
                  🔎
                </div>

                <span className="info-card-label">
                  STEP 01
                </span>

                <h3>
                  Find your applicable standard
                </h3>

                <p>
                  Start by identifying the Indian Standard
                  applicable to your product and its intended use.
                </p>

                <button
                  onClick={() => {
                    window.location.href = '/standards'
                  }}
                >
                  Explore Standards →
                </button>

              </div>

              {/* Testing */}

              <div className="certification-info-card">

                <div className="info-card-icon">
                  🧪
                </div>

                <span className="info-card-label">
                  STEP 04
                </span>

                <h3>
                  Understand product testing
                </h3>

                <p>
                  Learn about testing requirements and the role
                  of recognized laboratories in conformity assessment.
                </p>

                <button
                  onClick={() => {
                    window.location.href = '/assistant'
                  }}
                >
                  Ask BIS AI →
                </button>

              </div>

              {/* Compliance */}

              <div className="certification-info-card">

                <div className="info-card-icon">
                  🛡️
                </div>

                <span className="info-card-label">
                  COMPLIANCE
                </span>

                <h3>
                  Stay compliant
                </h3>

                <p>
                  Understand ongoing requirements, marking,
                  surveillance and maintaining conformity.
                </p>

                <button
                  onClick={() => {
                    window.location.href = '/assistant'
                  }}
                >
                  Get Guidance →
                </button>

              </div>

            </div>

            {/* ================= AI CARD ================= */}

            <section className="certification-ai-card">

              <div className="certification-ai-icon">
                ✨
              </div>

              <div className="certification-ai-content">

                <span>
                  BIS AI ASSISTANT
                </span>

                <h2>
                  Not sure where to start?
                </h2>

                <p>
                  Describe your product and let BIS Assist
                  help identify applicable standards, certification
                  requirements and the next steps.
                </p>

              </div>

              <button
                onClick={() => {
                  window.location.href = '/assistant'
                }}
              >
                Ask BIS AI →
              </button>

            </section>

          </div>

        </section>

      </main>
    </>
  )
}

export default Certification